# Generated by Django 5.0.2 on 2024-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('government', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
            options={
                'db_table': 'smm_municipality',
            },
        ),
    ]
